use_frameworks!

target 'DLNWiFiDetector_Example' do
  pod 'DLNWiFiDetector', :path => '../'

  target 'DLNWiFiDetector_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
