source 'https://github.com/CocoaPods/Specs.git'

#platform :ios, '7.0'
#warning: embedded dylibs/frameworks only run on iOS 8 or later
#use_frameworks!

target 'DLNWiFiDetector_Example' do
  pod 'DLNWiFiDetector', :path => '../'

  target 'DLNWiFiDetector_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase/Core'
  pod 'Expecta+Snapshots'
  end
end
